remote_theme: jekyll/minima

title: "Merve Tekgürler"
subtitle: "History Meets Computation"
description: >-
  In an effort to bridge the divide between the so-called 'Two Cultures' of
  Humanities and Sciences, Merve intertwines 18th-century history with
  contemporary AI technologies. This website acts as both a personal and
  academic hub, highlighting Merve's research, side projects, and non-academic writings.

url: "https://mervetekgurler.com"
baseurl: ""
timezone: "America/Los_Angeles"
locale: "en-US"

author:
  name: "Merve Tekgürler"
  location: "San Francisco, CA"

minima:
  skin: solarized
  date_format: "%B %-d, %Y"
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/MerveTekgurler" }
    - { platform: github, user_url: "https://github.com/mervetekgurler" }

header_pages:
  - _pages/publications.md
  - blog/index.html

paginate: 5
paginate_path: "/blog/page:num/"

include:
  - _pages

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - algolia-search.yml
  - _cheatsheet

permalink: "/:year/:month/:day/:title/"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 2..6

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
