theme: minima

title: "Merve Tekgürler"
description: "History Meets Computation"

url: "https://mervetekgurler.com"
baseurl: ""
timezone: "America/New_York"

author: "Merve Tekgürler"

minima:
  date_format: "%B %-d, %Y"

header_pages:
  - _pages/publications.md
  - _pages/projects.md
  - blog/index.html

paginate: 5
paginate_path: "/blog/page:num/"

include:
  - _pages

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

permalink: "/:year/:month/:day/:title/"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 2..6

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
